version: '3.8'
services:
  php:
    image: coolify:4
    build:
      dockerfile: Dockerfile
      context: ./docker/dev
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      PUID: "${USERID:-9999}"
      PGID: "${GROUPID:-9999}"
      SSL_MODE: 'off'
    volumes:
      - .:/var/www/html
    networks:
      - coolify
  postgres:
    image: postgres:15-alpine
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - db-coolify:/var/lib/postgresql/data
    networks:
      - coolify
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$DB_USERNAME",
          "-d",
          "db_prod"
        ]
      retries: 3
      timeout: 5s
  testing-host:
    container_name: coolify-testing-host
    image: coolify-testing-host
    build:
      dockerfile: Dockerfile
      context: ./docker/testing-host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/testing-host/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - coolify

volumes:
  db-coolify:
    driver: local

networks:
  coolify:
    driver: bridge
